blank_issues_enabled: false
contact_links:
  - name: Curious About Something?
    url: https://pkg.go.dev/github.com/sammat1388/go-sqlmock
    about: If you have a curious about something that isn't totally clear, please checkout the documentation first before creating an issue.